name: Build NtlmThief (Windows)

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug: list workspace
        run: |
          Write-Host "Working directory: $(pwd)"
          Get-ChildItem -Recurse -Force

      - name: Restore NuGet packages
        run: nuget restore NtlmThief.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build Solution (Release x64)
        run: msbuild.exe NtlmThief.sln /p:Configuration=Release /p:Platform=x64

      - name: List build output
        run: Get-ChildItem x64\Release -Recurse -Force

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NtlmThief-Release-x64
          path: |
            x64\Release\NtlmThief.exe
            x64\Release\**\*.dll
            x64\Release\**\*.pdb
