name: Build NtlmThief (Windows)

# Trigger on push to main or manual dispatch
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore NuGet packages
        run: nuget restore NtlmThief\NtlmThief.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build Release x64
        run: msbuild.exe NtlmThief\NtlmThief.sln /p:Configuration=Release /p:Platform=x64

      - name: Show files
        run: Get-ChildItem -Recurse -Force -File

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NtlmThief-Release-x64
          path: |
            NtlmThief\x64\Release\NtlmThief.exe
            NtlmThief\x64\Release\**\*.dll
            NtlmThief\x64\Release\**\*.pdb
