# .github/workflows/build-windows.yml
name: Build NtlmThief (Windows)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # Build the project file directly in Release|x64
      - name: Build NtlmThief.vcxproj (Release x64)
        run: msbuild.exe NtlmThief\NtlmThief.vcxproj /p:Configuration=Release /p:Platform=x64

      # (Optional) List everything so you can confirm where the EXE landed
      - name: Debug: show workspace files
        run: Get-ChildItem -Recurse -Force -File -ErrorAction Ignore

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: NtlmThief-Release-x64
          path: |
            NtlmThief\x64\Release\NtlmThief.exe
            NtlmThief\x64\Release\**\*.dll
            NtlmThief\x64\Release\**\*.pdb
