name: Build NtlmThief (Windows)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore NuGet packages (if any)
        run: nuget restore NtlmThief.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build Solution (Release x64)
        run: msbuild.exe NtlmThief.sln /p:Configuration=Release /p:Platform=x64

      # (Optional) Show directory tree so you can see exactly where the .exe landed
      - name: Debug: show folder layout
        run: dir /s /b .

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NtlmThief-Release
          # Grabs both Win32 and x64 Release outputs
          path: |
            NtlmThief/Release/**
            NtlmThief/x64/Release/**
