# .github/workflows/build-windows.yml
name: Build NtlmThief (Windows)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore NuGet (if needed)
        run: nuget restore NtlmThief.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build Win32 Release
        run: msbuild.exe NtlmThief.sln /p:Configuration=Release /p:Platform=Win32

      - name: Build x64 Release
        run: msbuild.exe NtlmThief.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload all build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NtlmThief-Release
          path: |
            NtlmThief/Release/**         # Win32-Release output
            NtlmThief/x64/Release/**      # x64-Release output
