# .github/workflows/build-windows.yml
name: Build NtlmThief (Windows)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - run: nuget restore NtlmThief.sln

      - uses: microsoft/setup-msbuild@v1

      - run: msbuild.exe NtlmThief.sln /p:Configuration=Release /p:Platform=x64

      # Debug step explicitly using cmd.exe so that `dir /s /b` works
      - name: Debug: list everything (cmd)
        shell: cmd
        run: dir /s /b .

      - uses: actions/upload-artifact@v4
        with:
          name: NtlmThief-Release
          path: |
            NtlmThief/Release/**
            NtlmThief/x64/Release/**
